blank_issues_enabled: true
contact_links:
 - name: Matrix Community Support
   url: "https://matrix.to/#/#matrix:matrix.org"
   about: General support questions can be asked here.
 - name: Matrix Security Policy
   url: https://www.matrix.org/security-disclosure-policy/
   about: Learn more about our security disclosure policy.
